theme: jekyll-theme-slate
title: نرم افزارهای مدیریت فروش و حسابداری رستوران
- title: Configuration
  url: configuration.html
description: تحلیل و بررسی راهکارهای نرم افزاری در فروش و بازاریابی
plugins:
  - jekyll-seo-tag

google_site_verification: LlHF3jdylfALGIZ31J9-KTW9i3yBep85wJwk680Z9Tg

