theme: jekyll-theme-slate
title: نرم افزارهای مدیریت فروش و حسابداری رستوران
toc:
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
description: تحلیل و بررسی راهکارهای نرم افزاری در فروش و بازاریابی
plugins:
  - jekyll-seo-tag

google_site_verification: LlHF3jdylfALGIZ31J9-KTW9i3yBep85wJwk680Z9Tg

